plugins {
    id 'maven-publish'
    id 'fabric-loom' version '1.17.12'
    id 'babric-loom-extension' version '1.16.1'
    id "com.modrinth.minotaur" version "2.+"
}

version = property("mod_version")
group = property("maven_group")

base {
    archivesName = project.archives_base_name
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

loom {
    if (project.hasProperty("accesswidener_name") && project.accesswidener_name.length() > 0) {
        accessWidenerPath = file("src/main/resources/${project.accesswidener_name}.accesswidener")
    }
    mixin {
        useLegacyMixinAp = false
    }
}

repositories {
    // Used for Babric Loom Extensions
    maven {
        name = "Babric"
        url = "https://maven.glass-launcher.net/babric"
    }

    // Used for many dependencies
    maven {
        name = "Glass Releases"
        url = "https://maven.glass-launcher.net/releases"
    }

    // Used for Snapshots
    maven {
        name = "Glass Snapshots"
        url = "https://maven.glass-launcher.net/snapshots"
    }

    // NyaRepo
    maven {
        name = "NyaRepo"
        url = "https://maven.fildand.cz/releases"
    }

    // Used for a StationAPI dependency.
    maven {
        name = "Froge Maven"
        url = "https://maven.minecraftforge.net/"
    }

    // Used for projects that do not have a maven repository, but do have a GitHub repository with working build scripts.
    maven {
        name = "Jitpack"
        url = "https://jitpack.io"
    }

    // Modrinth Maven
    exclusiveContent {
        forRepository {
            //noinspection ForeignDelegate
            maven {
                name = "Modrinth"
                url = "https://api.modrinth.com/maven"
            }
        }
        filter {
            includeGroup "maven.modrinth"
        }
    }

    mavenCentral()
}


dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    mappings "net.glasslauncher:biny:${project.yarn_mappings}:v2"
    modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"

    implementation "org.slf4j:slf4j-api:1.8.0-beta4"
    implementation "org.apache.logging.log4j:log4j-slf4j18-impl:2.17.2"
    implementation "me.carleslc:Simple-Yaml:1.8.4"

    modImplementation("net.modificationstation:StationAPI:${project.stapi_version}") {
        exclude group: "babric", module: "fabric-loader"
    }

    if (project.hasProperty("modmenu_version")) {
        modImplementation("net.danygames2014:modmenu:${project.modmenu_version}") {
            transitive = false
        }
    }

    if (project.hasProperty("glass_networking_version")) {
        modImplementation("net.glasslauncher.mods:glass-networking:${project.glass_networking_version}") {
            transitive = false
        }
    }

    if (project.hasProperty("gcapi_version")) {
        modImplementation("net.glasslauncher.mods:GlassConfigAPI:${project.gcapi_version}") {
            transitive = false
        }
    }

    if (project.hasProperty("alwaysmoreitems_version")) {
        modImplementation("net.glasslauncher.mods:AlwaysMoreItems:${project.alwaysmoreitems_version}") {
            transitive = false
        }
    }

    if (project.hasProperty("retrocommands_version")) {
        modImplementation("maven.modrinth:retrocommands:${project.retrocommands_version}-b1.7.3") {
            transitive = false
        }
    }

    if (project.hasProperty("whatsthis_version")) {
        modImplementation("net.danygames2014:WhatsThis:${project.whatsthis_version}") {
            transitive = false
        }
    }

    if (project.hasProperty("retroauth_version")) {
        modRuntimeOnly("maven.modrinth:retroauth:${project.retroauth_version}-b1.7.3") {
            transitive = false
        }
    }

    if (project.hasProperty("unitweaks_version")) {
        modRuntimeOnly("maven.modrinth:unitweaks:${project.unitweaks_version}-b1.7.3") {
            transitive = false
        }
    }

    modRuntimeOnly("maven.modrinth:fast-stapi-intro:2.0.0-b1.7.3") {
        transitive = false
    }

    modImplementation "maven.modrinth:cTg2WC1D:wHQvS6nF"

    implementation("com.github.GeyserMC:MCAuthLib:d9d773e5d50327c33898c65cd545a4f6ef3ba1b5") {
        transitive false
    }
}

processResources {
    inputs.property "version", project.version

    filesMatching("fabric.mod.json") {
        expand "version": project.version
    }
}

tasks.withType(JavaCompile).configureEach {
    it.options.release = 17
}

// Disables the generation of the .module file
tasks.withType(GenerateModuleMetadata).configureEach {
    enabled = false
}

// Gradle 9 fails the build if there are no tests, but we are using the test package for a test mod
tasks.withType(Test).configureEach {
    failOnNoDiscoveredTests = false
}

jar {
    from("LICENSE") {
        rename { "${it}_" + base.archivesName.get() }
    }
}


// configure the maven publication
publishing {
    publications {
        mavenJava(MavenPublication) {
            from components.java
        }
    }

    // See https://docs.gradle.org/current/userguide/publishing_maven.html for information on how to set up publishing.
    repositories {
        // Add repositories to publish to here.
        // Notice: This block does NOT have the same function as the block in the top level.
        // The repositories here will be used for publishing your artifact, not for
        // retrieving dependencies.
    }
}
