org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=false
fabric.loom.disableMinecraftVerification=true

# Fabric Properties
minecraft_version=b1.7.3
yarn_mappings=b1.7.3+e0778a3
loader_version=0.19.3

# Mod Properties
mod_version=0.4.2
maven_group=com.github.zr0n1.multiproto
archives_base_name=multiproto

# Dependencies
stapi_version=2.0.0-alpha.6.2
glass_networking_version=1.0.7
gcapi_version=3.2.5
alwaysmoreitems_version=1.10.0
modmenu_version=1.1.1
bhcreative_version=0.4.9
spawneggs_version=1.12.1
retrocommands_version=0.5.10
whatsthis_version=1.2.0

# Runtime only mods
debugutilities_version=1.0.0
retroauth_version=1.1.1
unitweaks_version=0.28.0